Mokkery Gradle Plugin
lupuuss/Mokkery pull request #21
Opened 2024-07-07 13:44 UTC by kigya

For the Docosaurus website, added a description of what needs to be considered when working with Mokkery and Convention Plugins.

<img width="845" alt="image" src="https://github.com/lupuuss/Mokkery/assets/73034324/1c6fbfd4-5b76-4f65-a433-96b62cdeb332">

2024-07-07 21:04 UTC, lupuuss requested changes
Thanks you for contribution! I've recently discovered this inconvenience. For know, I will add this section, but I will try to remove this inconvenience in the future.

2024-07-08 11:56 UTC, lupuuss commented on website/docs/Setup.mdx
> +    implementation("dev.mokkery:mokkery-gradle:2.1.1)
```suggestion
    implementation("dev.mokkery:mokkery-gradle:2.1.1")
```

2024-07-08 16:01 UTC, kigya commented on website/docs/Setup.mdx
> +        maven {
Yes, I have tested it and it works. Good point

2024-07-08 16:02 UTC, kigya commented on website/docs/Setup.mdx
> +
Extracted as a separate section

2024-07-08 16:02 UTC, kigya commented on website/docs/Setup.mdx
> +    implementation("dev.mokkery:mokkery-gradle:2.1.1)
Good catch, fixed

2024-07-08 16:03 UTC, kigya commented
Updated version: 

![](https://github.com/lupuuss/Mokkery/assets/73034324/006487e9-3b13-41fe-8d9d-d50ac595b753)

2024-07-08 16:09 UTC, lupuuss approved these changes

2024-07-09 16:05 UTC, merged